### ISSUE TITLE
Move profile picture

### ISSUE THREAD

**Issue by admiralorbiter** [admiralorbiter/DataDeck#12]
Currently the profile picture on the session_details page is under the info section, but lets add it to the row instead so it will be in line with the other components and keep the height of this sticky header smaller.

![image](https://github.com/user-attachments/assets/f527db3c-cf75-4a24-99de-ea964e2b1c62)

**Comment by angelo-fantino** [comment]
Greetings,

Sorry, but I cannot understand your issue. Would you mind please rewriting it more clearly?

**Comment by admiralorbiter** [comment]
Absolutely! I'm looking to move the avatar profile picture of the 'student' from below the "Info pane" that contains the Title, School, and Session code and move it so it is between the info pane and the badge pane. Below is an image where I thought the picture would best fit, but I'm open to the profile pic placement. 

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/cf300c58-e192-4338-b122-e51e75fb3336">

The goal is to reduce the height of that component by putting everything into a single row.
