### ISSUE TITLE
Background Color Change

### ISSUE THREAD

**Issue by admiralorbiter** [admiralorbiter/DataDeck#9]
For the sticky header component for the main session page, I want the background behind the header to match the blue E6FDF9 instead of white. 
![image](https://github.com/user-attachments/assets/cbc46623-ef1c-4327-9896-04cd43a5d360)

**Comment by cduarte3** [comment]
Hi @admiralorbiter, can you please assign me to this issue?

If possible, can you please add the label of “hacktoberfest” as well?

**Comment by admiralorbiter** [comment]
Absolutely! Thanks for your contribution.

**Comment by cduarte3** [comment]
No problem, happy to contribute!
